In [3]:
import pandas as pd
import numpy as np

In [4]:
data ={
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"], 
    "Age": [25, 30, 35, np.nan, 29, 25], 
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"], 
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}

In [8]:
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [8]:
df =pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [14]:
#first few records of the table
df.head(2)

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0

In [15]:
#Last records in the table
df.tail(3)

    Name   Age Department   Salary
3  David   NaN         IT  62000.0
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

In [9]:
# Data types
df.dtypes

Name           object
Age           float64
Department     object
Salary        float64
dtype: object

In [19]:
#loc and iloc
df.iloc[1:3,:2]

      Name   Age
1      Bob  30.0
2  Charlie  35.0

In [18]:
df.loc[1:2, ["Age","Department"]]

    Age Department
1  30.0         IT
2  35.0    Finance

In [21]:
df[['Age',"Department"]]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [22]:
df.drop("Age" , axis =1)

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [23]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [32]:
df.shape

(6, 4)

In [33]:
df.drop("Age" , axis =1, inplace = True)

In [25]:
df

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [34]:
df.shape

(6, 3)

In [43]:
#Summary of data frame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [42]:
#get basic statistics of numerical columns
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

In [10]:
#check for missing values in each column 
df.isnull().sum

<bound method DataFrame.sum of     Name    Age  Department  Salary
0  False  False       False   False
1  False  False       False   False
2  False  False       False   False
3  False   True       False   False
4  False  False       False    True
5  False  False       False   False>

#### Broadcasting

In [51]:
df['Salary'] = df['Salary']+5000

In [53]:
df['Salary']

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

#### Rename column

In [13]:
df.rename(columns ={"Department":"Dept"}, inplace =True)

In [57]:
df

      Name   Age     Dept   Salary
0    Alice  25.0       HR  55000.0
1      Bob  30.0       IT  65000.0
2  Charlie  35.0  Finance  75000.0
3    David   NaN       IT  67000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  55000.0

In [11]:
# Get the unique values for categorical columns
df['Salary'].unique()

array([50000., 60000., 70000., 62000.,    nan])

In [59]:
df['Dept'].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [14]:
#Get the count of unique values for categorical columns
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [61]:
df["Promoted Salary"]=df["Salary"]*10

In [62]:
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [15]:
df.duplicated().sum()

1