In [1]:
import pandas as pd
import numpy as np

In [2]:
data ={
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"], 
    "Age": [25, 30, 35, np.nan, 29, 25], 
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"], 
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}

In [3]:
df =pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [4]:
df.isnull().sum()

Name          0
Age           1
Department    0
Salary        1
dtype: int64

In [6]:
df.dropna()  #drop null values

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
5    Alice  25.0         HR  50000.0

In [7]:
df.dropna(how ="any") #any row that had null value

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
5    Alice  25.0         HR  50000.0

In [8]:
df.dropna(how = 'all')  #if all the values in a row is null

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [9]:
df.fillna(0) #NOOB Method

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   0.0         IT  62000.0
4      Eve  29.0         HR      0.0
5    Alice  25.0         HR  50000.0

In [10]:
# Fill missing values in stock with the mean of the column
df['Age'].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [11]:
# Fill missing values in stock with the median of the column
df['Salary'].fillna(df["Salary"].median())

0    50000.0
1    60000.0
2    70000.0
3    62000.0
4    60000.0
5    50000.0
Name: Salary, dtype: float64

In [12]:
df['Age'].fillna(method = "ffill")

C:\Users\jainv\AppData\Local\Temp\ipykernel_20392\2879445670.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Age'].fillna(method = "ffill")

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [15]:
df["Name"]=df["Name"].replace("Charlie","Rose")

In [16]:
df

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0
2   Rose  35.0    Finance  70000.0
3  David   NaN         IT  62000.0
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

### Duplicates:

In [21]:
df_dup = df[df.duplicated( keep ="last")]

In [22]:
df_dup

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0

In [6]:
# Remove duplicate rowa
df = df.drop_duplicates()

In [26]:
df

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0
2   Rose  35.0    Finance  70000.0
3  David   NaN         IT  62000.0
4    Eve  29.0         HR      NaN

### Invalid Values

In [31]:
df.loc[:, "Promoted Salary"] = df["Salary"] * 10

In [32]:
df

    Name   Age Department   Salary  Promoted Salary
0  Alice  25.0         HR  50000.0         500000.0
1    Bob  30.0         IT  60000.0         600000.0
2   Rose  35.0    Finance  70000.0         700000.0
3  David   NaN         IT  62000.0         620000.0
4    Eve  29.0         HR      NaN              NaN

In [33]:
df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x>650000 else x)

C:\Users\jainv\AppData\Local\Temp\ipykernel_20392\929332611.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x>650000 else x)

In [34]:
df

    Name   Age Department   Salary  Promoted Salary
0  Alice  25.0         HR  50000.0         500000.0
1    Bob  30.0         IT  60000.0         600000.0
2   Rose  35.0    Finance  70000.0          70000.0
3  David   NaN         IT  62000.0         620000.0
4    Eve  29.0         HR      NaN              NaN

In [38]:
name  = "alice _fernandes"
df[["first_name","last_name"]] = df["Name"].str.splt("_")

### apply and lambda

In [41]:
def multiplying_age(x):
    return x*2
df["Age"] = df["Age"].apply(multiplying_age)

C:\Users\jainv\AppData\Local\Temp\ipykernel_20392\1805664462.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(multiplying_age)

In [42]:
df

    Name   Age Department   Salary  Promoted Salary
0  Alice  50.0         HR  50000.0         500000.0
1    Bob  60.0         IT  60000.0         600000.0
2   Rose  70.0    Finance  70000.0          70000.0
3  David   NaN         IT  62000.0         620000.0
4    Eve  58.0         HR      NaN              NaN

In [43]:
df["Age"] = df["Age"].apply(lambda x: x/2)

C:\Users\jainv\AppData\Local\Temp\ipykernel_20392\1345931692.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(lambda x: x/2)

In [44]:
df

    Name   Age Department   Salary  Promoted Salary
0  Alice  25.0         HR  50000.0         500000.0
1    Bob  30.0         IT  60000.0         600000.0
2   Rose  35.0    Finance  70000.0          70000.0
3  David   NaN         IT  62000.0         620000.0
4    Eve  29.0         HR      NaN              NaN