In [1]:
import pandas as pd
import numpy as np

In [2]:
department_info = {
"Department": ["HR", "IT", "Finance"],
"Location": ["New York", "San Francisco", "Chicago"],
"Manager": ["Laura", "Steve", "Nina"]
}

In [5]:
df2 = pd.DataFrame(department_info)
df2

  Department       Location Manager
0         HR       New York   Laura
1         IT  San Francisco   Steve
2    Finance        Chicago    Nina

In [6]:
data ={
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"], 
    "Age": [25, 30, 35, np.nan, 29, 25], 
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"], 
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}

In [7]:
df =pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

### concat

In [8]:
pd.concat([df,df2])

      Name   Age Department   Salary       Location Manager
0    Alice  25.0         HR  50000.0            NaN     NaN
1      Bob  30.0         IT  60000.0            NaN     NaN
2  Charlie  35.0    Finance  70000.0            NaN     NaN
3    David   NaN         IT  62000.0            NaN     NaN
4      Eve  29.0         HR      NaN            NaN     NaN
5    Alice  25.0         HR  50000.0            NaN     NaN
0      NaN   NaN         HR      NaN       New York   Laura
1      NaN   NaN         IT      NaN  San Francisco   Steve
2      NaN   NaN    Finance      NaN        Chicago    Nina

In [9]:
pd.concat([df,df2], axis =1)

      Name   Age Department   Salary Department       Location Manager
0    Alice  25.0         HR  50000.0         HR       New York   Laura
1      Bob  30.0         IT  60000.0         IT  San Francisco   Steve
2  Charlie  35.0    Finance  70000.0    Finance        Chicago    Nina
3    David   NaN         IT  62000.0        NaN            NaN     NaN
4      Eve  29.0         HR      NaN        NaN            NaN     NaN
5    Alice  25.0         HR  50000.0        NaN            NaN     NaN

In [14]:
pd.merge(df,df2, on ="Department")

      Name   Age Department   Salary       Location Manager
0    Alice  25.0         HR  50000.0       New York   Laura
1      Eve  29.0         HR      NaN       New York   Laura
2    Alice  25.0         HR  50000.0       New York   Laura
3      Bob  30.0         IT  60000.0  San Francisco   Steve
4    David   NaN         IT  62000.0  San Francisco   Steve
5  Charlie  35.0    Finance  70000.0        Chicago    Nina

## Importing file

In [16]:
data = pd.read_csv("gas_prices.csv")

In [17]:
data

,Year,Australia,Canada,France,Germany,Italy,Japan,Mexico,South Korea,UK,USA
0,1990,NaN,1.87,3.63,2.65,4.59,3.16,1.00,2.05,2.82,1.16
1,1991,1.96,1.92,3.45,2.90,4.50,3.46,1.30,2.49,3.01,1.14
2,1992,1.89,1.73,3.56,3.27,4.53,3.58,1.50,2.65,3.06,1.13
3,1993,1.73,1.57,3.41,3.07,3.68,4.16,1.56,2.88,2.84,1.11
4,1994,1.84,1.45,3.59,3.52,3.70,4.36,1.48,2.87,2.99,1.11
5,1995,1.95,1.53,4.26,3.96,4.00,4.43,1.11,2.94,3.21,1.15
6,1996,2.12,1.61,4.41,3.94,4.39,3.64,1.25,3.18,3.34,1.23
7,1997,2.05,1.62,4.00,3.53,4.07,3.26,1.47,3.34,3.83,1.23
8,1998,1.63,1.38,3.87,3.34,3.84,2.82,1.49,3.04,4.06,1.06
9,1999,1.72,1.52,3.85,3.42,3.87,3.27,1.79,3.80,4.29,1.17
10,2000,1.94,1.86,3.80,3.45,3.77,3.65,2.01,4.18,4.58,1.51
11,2001,1.71,1.72,3.51,3.40,3.57,3.27,2.20,3.76,4.13,1.46
12,2002,1.76,1.69,3.62,3.67,3.74,3.15,2.24,3.84,4.16,1.36
13,2003,2.19,1.99,4.35,4.59,4.53,3.47,2.04,4.11,4.70,1.59
14,2004,2.72,2.37,4.99,5.24,5.29,3.93,2.03,4.51,5.56,1.88
15,2005,3.23,2.89,5.46,5.66,5.74,4.28,2.22,5.28,5.97,2.30
16,2006,3.54,3.26,5.88,6.03,6.10,4.47,2.31,5.92,6.36,2.59
17,2007,3.85,3.59,6.60,6.88,6.73,4.49,2.40,6.21,7.13,2.80
18,2008,4.45,4.08,7.51,7.75,7.63,5.74,2.45,5.83,7.42,3.27

In [18]:
data.shape

(19, 11)

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Year         19 non-null     int64
 1   Australia    18 non-null     float64
 2   Canada       19 non-null     float64
 3   France       19 non-null     float64
 4   Germany      19 non-null     float64
 5   Italy        19 non-null     float64
 6   Japan        19 non-null     float64
 7   Mexico       19 non-null     float64
 8   South Korea  19 non-null     float64
 9   UK           19 non-null     float64
 10  USA          19 non-null     float64
dtypes: float64(10), int64(1)
memory usage: 1.8 KB

In [ ]:
# data['date'] =pd.to_datetime(data['date'])